# Generated by Django 4.2.1 on 2023-06-03 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_product_rating_remove_product_reviews_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='specifications',
            field=models.ManyToManyField(blank=True, null=True, related_name='specifications', to='api.specification'),
        ),
    ]
