# Generated by Django 4.2.1 on 2023-06-04 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_product_specifications'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='free_delivery',
            new_name='freeDelivery',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='full_description',
            new_name='fullDescription',
        ),
        migrations.AlterField(
            model_name='product',
            name='specifications',
            field=models.ManyToManyField(blank=True, null=True, related_name='product', to='api.specification'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product', to='api.tag'),
        ),
    ]
