# Generated by Django 4.2.1 on 2023-06-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_free_delivery_product_freedelivery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='specifications',
            field=models.ManyToManyField(default=[], related_name='products', to='api.specification'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(default=[], related_name='products', to='api.tag'),
        ),
    ]
