# Generated by Django 4.2.1 on 2023-06-04 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_product_specifications_remove_product_tags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(default=[], related_name='products', to='api.image'),
        ),
    ]
