# Generated by Django 4.2.1 on 2023-06-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_profile_fullname_alter_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='alt',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
