# Generated by Django 4.2.1 on 2023-06-05 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_image_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
