# Generated by Django 4.2.1 on 2023-06-06 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='limited_edition',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='api.product'),
        ),
    ]
