# Generated by Django 4.2.1 on 2023-06-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_product_limited_edition_alter_review_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_sold',
            field=models.IntegerField(default=0),
        ),
    ]
