# Generated by Django 4.2.1 on 2023-06-06 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_product_product_sold'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_sold',
            new_name='sold',
        ),
    ]
