# Generated by Django 4.2.1 on 2023-06-08 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_rename_sale_price_sale_saleprice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='reviews',
        ),
    ]
