# Generated by Django 4.2.1 on 2023-06-17 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_remove_order_delivery_type_remove_order_payment_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='create_at',
            new_name='createdAt',
        ),
    ]
