# Generated by Django 4.2.1 on 2023-06-19 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deliveryType',
            field=models.CharField(default='reg', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='paymentType',
            field=models.CharField(default='online', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(default=[], related_name='product', to='api.image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='specifications',
            field=models.ManyToManyField(blank=True, default=[], related_name='product', to='api.specification'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, default=[], related_name='product', to='api.tag'),
        ),
    ]
